runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bom
  script: main.app
  login: admin

#[START env]
env_variables:
  PUBSUB_TOPIC: #topicname
  GCLOUD_PROJECT: #projectname
#[END env]
