runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bom
  script: main.app
  login: admin

#[START env]
env_variables:
  PUBSUB_TOPIC: bom_weather_data_new
  GCLOUD_PROJECT: focus-antler-254823
#[END env]